# Generated by Django 2.1.2 on 2019-01-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('url', models.CharField(blank=True, help_text='Not required if running locally', max_length=256, null=True)),
                ('local', models.BooleanField(default=True, help_text='Check if running locally')),
                ('active', models.BooleanField(default=True)),
                ('manage', models.CharField(help_text="Full path to the directory that the project's manage.py file is in", max_length=256, unique=True)),
                ('settings', models.CharField(help_text="Full path to the directory that the project's settings.py file is in", max_length=256, unique=True)),
                ('virtual_env', models.CharField(blank=True, help_text="Ful path to the directory that your virtual environment's bin directory is in", max_length=256, null=True)),
            ],
        ),
    ]
