# Generated by Django 2.1.2 on 2019-01-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(help_text='User-friendly service name', max_length=32),
        ),
        migrations.AlterField(
            model_name='service',
            name='settings',
            field=models.CharField(help_text="Relative path to the project's settings.py file", max_length=256),
        ),
    ]
