# Generated by Django 2.1.2 on 2019-03-25 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microservices', '0002_auto_20190111_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='command_name',
            field=models.CharField(blank=True, help_text='manage.py command to run if not "runserver"', max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='virtual_env',
            field=models.CharField(blank=True, help_text="Full path to the directory that your virtual environment's bin directory is in", max_length=256, null=True),
        ),
    ]
